### ISSUE TITLE
What to do about xgboost?

### ISSUE THREAD

**Issue by egillax** [OHDSI/DeepPatientLevelPredictionModule#3]
@jreps, 

In our planned study we plan to run xgboost along with lasso and the deep learning models. xgboost is a suggest dependancy of the PLP. I needed to add it to the renv file to run the study on IPCI. 

The question is if I should add it here in the module. It's not needed to run deepPLP. Maybe in the ideal case people would use the PLP module for the PLP models and the deepPLP one only for the deep models? 

What do you think?

**Comment by jreps** [comment]
yeah - lets use PLP module for standard classifiers and DeepPLP module just for the deep learning ones.  

I need to add xgboost (plus any other important dependencies in the suggests) to the renv for the PLP module (it should be there but I forgot to specify to include it as an extra and it is missed by renv by default due to it being in suggests).
